### 授权码模式
### 第一步申请授权码(浏览器请求)
### 地址: {{auth_host}}/oauth/authorize?client_id=ILearnWebApp&response_type=code&scope=all&redirect_uri=http://www.ilearn1026.com
### 第二步申请令牌
POST {{auth_host}}/auth/oauth/token?client_id=ILearnWebApp&client_secret=ILearn1026&grant_type=authorization_code&code=UWK9JR&redirect_uri=http://www.ilearn1026.com

### 密码模式
POST {{auth_host}}/auth/oauth/token?client_id=ILearnWebApp&client_secret=ILearn1026&grant_type=password&username=xiaoxiaoyi&password=1026

### 密码模式(JWT令牌)
POST {{auth_host}}/auth/oauth/token?client_id=ILearnWebApp&client_secret=ILearn1026&grant_type=password&username={"authorizeType":"password", "userName":"xiaoxiaoyi", "password":"1026"}

### 校验jwt令牌
POST {{auth_host}}/auth/oauth/check_token?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsiaWxlYXJuIl0sInVzZXJfbmFtZSI6IntcImNvbXBhbnlJZFwiOlwiMTIzMjE0MTQyNVwiLFwiY3JlYXRlVGltZVwiOlwiMjAyMi0wOS0yOCAwODozMjowM1wiLFwiaWRcIjpcIjUyXCIsXCJuYW1lXCI6XCJN6ICB5biIXCIsXCJzZXhcIjpcIjFcIixcInN0YXR1c1wiOlwiXCIsXCJ1c2VybmFtZVwiOlwidDFcIixcInV0eXBlXCI6XCIxMDEwMDJcIn0iLCJzY29wZSI6WyJhbGwiXSwiZXhwIjoxNjc4MTAyNDg2LCJhdXRob3JpdGllcyI6WyJpbGVhcm5fdGVhY2htYW5hZ2VyX2NvdXJzZV9iYXNlIiwiaWxlYXJuX3RlYWNobWFuYWdlcl9jb3Vyc2VfcGxhbiIsImlsZWFybl90ZWFjaG1hbmFnZXJfY291cnNlX2RlbCIsImlsZWFybl90ZWFjaG1hbmFnZXJfY291cnNlX21hcmtldCIsImNvdXJzZV9maW5kX2xpc3QiLCJpbGVhcm5fdGVhY2htYW5hZ2VyX2NvdXJzZV9saXN0IiwiaWxlYXJuX3RlYWNobWFuYWdlciIsImlsZWFybl90ZWFjaG1hbmFnZXJfY291cnNlX3B1Ymxpc2giLCJpbGVhcm5fdGVhY2htYW5hZ2VyX2NvdXJzZSIsImlsZWFybl90ZWFjaG1hbmFnZXJfY291cnNlX2FkZCJdLCJqdGkiOiJhNzE4ZjE5NS0zMzE2LTQyY2EtYjg0Ni1hZTU4MjU5NzZmZjMiLCJjbGllbnRfaWQiOiJJTGVhcm5XZWJBcHAifQ.p3QSI8X-z7J9j03Ly-4VJ3PfdinaxT3J54V_Bt7X-D0