### 课程查询接口
POST {{content_host}}/content/course/list?pageNo=1&pageSize=3
Content-Type: application/json

{
  "auditStatus": "202004",
  "courseName": "java",
  "publishStatus": "203001"
}

### 课程分类接口
GET {{content_host}}/content/course-category/tree-nodes

### 添加课程
POST {{content_host}}/content/course
Content-Type: application/json

{
  "mt": "1-1",
  "st": "1-1-1",
  "name": "",
  "teachmode": "200002",
  "users": "初级人员",
  "tags": "测试标签",
  "grade": "204001",
  "description": "课程介绍",
  "objectives": "适用人群",
  "charge": "",
  "price": 0,
  "originalPrice": 0,
  "qq": "123123",
  "wechat": "xxyxxy",
  "phone": "123414141",
  "validDays": 365
}

### 根据课程id获取课程信息 123为要查询的课程ID
GET {{content_host}}/content/course/123

### 更新课程信息
PUT {{content_host}}/content/course
Content-Type: application/json

{
  "courseId": "123",
  "mt": "1-1",
  "st": "1-1-1",
  "name": "",
  "teachmode": "200002",
  "users": "初级人员",
  "tags": "测试标签",
  "grade": "204001",
  "description": "课程介绍",
  "objectives": "适用人群",
  "charge": "",
  "price": 0,
  "originalPrice": 0,
  "qq": "123123",
  "wechat": "xxyxxy",
  "phone": "123414141",
  "validDays": 365
}

### 根据课程信息获取对应的教学计划
GET {{content_host}}/content/teachplan/117/tree-nodes
Content-Type: application/json