### 授权码模式
### 第一步申请授权码(浏览器请求)
### 地址: {{auth_host}}/oauth/authorize?client_id=ILearnWebApp&response_type=code&scope=all&redirect_uri=http://www.ilearn1026.com
### 第二步申请令牌
POST {{auth_host}}/auth/oauth/token?client_id=ILearnWebApp&client_secret=ILearn1026&grant_type=authorization_code&code=UWK9JR&redirect_uri=http://www.ilearn1026.com

### 密码模式
POST {{auth_host}}/auth/oauth/token?client_id=ILearnWebApp&client_secret=ILearn1026&grant_type=password&username=xiaoxiaoyi&password=1026

### 密码模式(JWT令牌)
POST {{auth_host}}/auth/oauth/token?client_id=ILearnWebApp&client_secret=ILearn1026&grant_type=password&username={"authorizeType":"password", "checkCode":"xyx"}&password=1026

### 校验jwt令牌
POST {{auth_host}}/auth/oauth/check_token?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsiaWxlYXJuIl0sInVzZXJfbmFtZSI6IntcImJpcnRoZGF5XCI6XCIyMDAxLTAyLTI4IDEzOjE4OjQ1XCIsXCJjZWxscGhvbmVcIjpcIjQxNTM1NjEzXCIsXCJjcmVhdGVUaW1lXCI6XCIyMDIzLTAyLTI2IDEzOjE5OjQwXCIsXCJlbWFpbFwiOlwiMTIzMTIzQHFxLmNvbVwiLFwiaWRcIjpcIjEwMjZcIixcIm5hbWVcIjpcInhpYW95aVwiLFwibmlja25hbWVcIjpcInhpYW94aWFveWlcIixcInFxXCI6XCIyMTM1MTUxXCIsXCJzZXhcIjpcIjFcIixcInN0YXR1c1wiOlwiMVwiLFwidXNlcm5hbWVcIjpcInhpYW94aWFveWlcIixcInV0eXBlXCI6XCIxMDEwMDFcIn0iLCJzY29wZSI6WyJhbGwiXSwiZXhwIjoxNjc3NDAwNTIxLCJhdXRob3JpdGllcyI6WyJ0ZXN0Il0sImp0aSI6IjI1ZmI5MzcwLWM5YjMtNDc3Ny05ODBkLWYwYjRlNWI3M2EwMiIsImNsaWVudF9pZCI6IklMZWFybldlYkFwcCJ9.h121yPVZkB51PnFn8uaL9buoObsLvK8sWIW3sj3UlaU